// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkcdwxkqzohibsxglhyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprY2R3eGtxem9oaWJzeGdsaHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1ODI3ODEsImV4cCI6MjA4MDE1ODc4MX0.EBubNPHIiiyIgDgQdb6h_25ocIfWtaZ-6oBXaZl0Y0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
